# Setup
title:               'Projet de session &middot; IFT6758'
tagline:             Blog
description:         ''
url:                 ''
baseurl:             ''
paginate:            3
permalink:           pretty

# About/contact
author:
  name:              Daniel Lofeodo, Nathan Cormerais
  email:             daniel.lofeodo@umontreal.ca, nathan.cormerais@umontreal.ca

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
